# Generated by Django 5.2.8 on 2026-03-01 07:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company_logo', models.URLField(blank=True, max_length=1000, null=True)),
                ('company', models.CharField(max_length=255)),
                ('biography', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('location', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('FL', 'Freelance'), ('IN', 'Internship')], default='FT', max_length=2)),
                ('job_mode', models.CharField(choices=[('ON', 'Onsite'), ('HY', 'Hybrid'), ('RE', 'Remote')], default='ON', max_length=2)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application_link', models.URLField(blank=True, max_length=500, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
