# Generated by Django 5.2.8 on 2026-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='job',
            name='edit_info',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_mode',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(max_length=2),
        ),
    ]
