# Generated by Django 5.2.8 on 2026-03-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_super_staff',
            field=models.BooleanField(default=False),
        ),
    ]
